import type { AdminUserType, UserType } from "./types/user";

export const dummyAdmins: Array<AdminUserType> = [
  {
    id: "100",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "101",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "102",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "103",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    id: "123",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    id: "234",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    id: "345",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
];

export const dummyUsers: Array<UserType> = [
  {
    id: "100",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "101",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "102",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "103",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "104",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "105",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "106",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "107",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "108",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "109",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "110",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "111",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "112",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "113",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "114",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "115",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "116",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "117",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "118",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "119",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "120",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "121",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "122",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "123",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "124",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "125",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "126",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "127",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "128",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    id: "129",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
];
