import type { AdminUserType, UserType } from "./types/user";

export const dummyAdmins: Array<AdminUserType> = [
  {
    _id: "100",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "101",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "102",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "103",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "104",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "105",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "106",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "107",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "108",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "109",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "110",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "111",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "112",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "113",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "114",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "115",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "116",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "117",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "118",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "119",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "120",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "121",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "122",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "123",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "124",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "125",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "126",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
  {
    _id: "127",
    role: "super admin",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail@gmail.com",
  },
  {
    _id: "128",
    role: "admin",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    email: "samplemail2@gmail.com",
  },
  {
    _id: "129",
    role: "super admin",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    email: "samplemail3@gmail.com",
  },
];

export const dummyUsers: Array<UserType> = [
  {
    _id: "69421",
    email: "irvinkierpresto26@gmail.com",
    username: "erbeeen",
    firstName: "Irvin Kier",
    lastName: "Presto",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "100",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "101",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "102",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "103",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "104",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "105",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "106",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "107",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "108",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "109",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "110",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "111",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "112",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "113",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "114",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "115",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "116",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "117",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "118",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "119",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "120",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "121",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "asdfqwerzxcajsdkf;asdlkfjas;dflkjasd;lfkjasd;llfkjasd;lfkasd;flkjasd;lfkjasd;lfkajsd;flkj",
  },
  {
    _id: "122",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "123",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "124",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "125",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "126",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "127",
    email: "samplemail@gmail.com",
    username: "asdf",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "128",
    email: "samplemail2@gmail.com",
    username: "sdfg",
    firstName: "Jane",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
  {
    _id: "129",
    email: "samplemail3@gmail.com",
    username: "dfgh",
    firstName: "John",
    lastName: "Doe",
    password: "a;sdlkfjweporuwe;l;({[`$&*({[`@);elkr",
  },
];
